export interface GlossaryTerm {
  id: string;
  name_es: string;
  name_en: string;
  definition_es: string;
  definition_en: string;
  patterns_es: string[];
  patterns_en: string[];
}

export const GLOSSARY_DATA: GlossaryTerm[] = [
  {
    id: "attenuation",
    name_es: "Atenuación",
    name_en: "Attenuation",
    definition_es: "El porcentaje de azúcares en el mosto que la levadura ha convertido en alcohol y dióxido de carbono durante la fermentación. Una atenuación alta resulta en una cerveza con final seco, mientras que una atenuación baja deja más azúcares residuales, dulzor y cuerpo.",
    definition_en: "The percentage of sugars in the wort that the yeast has converted into alcohol and carbon dioxide during fermentation. High attenuation results in a dry beer, while low attenuation leaves more residual sugars, sweetness, and body.",
    patterns_es: ["atenuaci[oó]n", "atenuaciones"],
    patterns_en: ["attenuation", "attenuations", "attenuated"]
  },
  {
    id: "body",
    name_es: "Cuerpo",
    name_en: "Body",
    definition_es: "La sensación táctil de peso, viscosidad y plenitud en la boca al degustar una cerveza. Varía desde ligero o acuoso (como agua) hasta pleno, denso y cremoso (como leche o licor), influenciado por las proteínas de la malta y azúcares no fermentables.",
    definition_en: "The tactile sensation of weight, viscosity, and fullness in the mouth when tasting a beer. It ranges from light or watery (like water) to full, dense, and creamy (like milk or liqueur), influenced by malt proteins and non-fermentable sugars.",
    patterns_es: ["cuerpo", "cuerpos"],
    patterns_en: ["body", "bodies"]
  },
  {
    id: "esters",
    name_es: "Ésteres",
    name_en: "Esters",
    definition_es: "Compuestos aromáticos volátiles producidos por la levadura durante la fermentación que aportan notas frutales. Los más comunes recuerdan a plátano (acetato de isoamilo), pera, manzana, solvente o fresa, siendo cruciales en cervezas belgas y alemanas de trigo.",
    definition_en: "Volatile aromatic compounds produced by yeast during fermentation that contribute fruity notes. The most common resemble banana (isoamyl acetate), pear, apple, solvent, or strawberry, being crucial in Belgian and German wheat beers.",
    patterns_es: ["[eé]steres", "[eé]ster"],
    patterns_en: ["esters", "ester"]
  },
  {
    id: "phenols",
    name_es: "Fenoles",
    name_en: "Phenols",
    definition_es: "Compuestos químicos aromáticos producidos por levaduras salvajes o cepas especializadas (como las de trigo alemanas o belgas). Aportan notas especiadas a clavo de olor, pimienta, o en exceso, cualidades medicinales, a plástico, curita o ahumado.",
    definition_en: "Aromatic chemical compounds produced by wild yeast or specialized yeast strains (such as German wheat or Belgian styles). They contribute spicy notes of clove, pepper, or in excess, medicinal, plastic, band-aid, or smoky qualities.",
    patterns_es: ["fenoles", "fenol", "fen[oó]lic[oa]s?"],
    patterns_en: ["phenols", "phenol", "phenolic"]
  },
  {
    id: "diacetyl",
    name_es: "Diacetilo",
    name_en: "Diacetyl",
    definition_es: "Un compuesto de subproducto de la fermentación que aporta un aroma y sabor a mantequilla, palomitas de maíz con mantequilla o toffee (butterscotch), acompañado a menudo por una sensación física aceitosa en la lengua. Defecto grave en la mayoría de lagers.",
    definition_en: "A fermentation by-product compound that contributes a buttery, buttered popcorn, or butterscotch aroma and flavor, often accompanied by an oily physical slickness on the tongue. A major flaw in most lagers.",
    patterns_es: ["diacetilo"],
    patterns_en: ["diacetyl"]
  },
  {
    id: "dms",
    name_es: "DMS (Sulfuro de Dimetilo)",
    name_en: "DMS (Dimethyl Sulfide)",
    definition_es: "Un compuesto azufrado que aporta notas aromáticas a maíz dulce cocido, vegetales enlatados o agua de cocción de col. Se genera al calentar la malta y se elimina mediante un hervido vigoroso y abierto del mosto. Común en lagers pálidas.",
    definition_en: "A sulfur compound that contributes aromatic notes of sweet cooked corn, canned vegetables, or cabbage boiling water. It is generated by heating malt and removed by a vigorous, open boil of the wort. Common in pale lagers.",
    patterns_es: ["dms", "sulfuro de dimetilo"],
    patterns_en: ["dms", "dimethyl sulfide"]
  },
  {
    id: "wort",
    name_es: "Mosto",
    name_en: "Wort",
    definition_es: "El líquido dulce y rico en azúcares extraído durante el proceso de maceración del grano. Es la 'cerveza sin fermentar' que posteriormente se hierve con lúpulo y se inocula con levadura para iniciar la fermentación.",
    definition_en: "The sweet, sugar-rich liquid extracted during the grain mashing process. It is the 'unfermented beer' that is subsequently boiled with hops and pitched with yeast to start fermentation.",
    patterns_es: ["mosto", "mostos"],
    patterns_en: ["wort", "worts"]
  },
  {
    id: "mashing",
    name_es: "Maceración",
    name_en: "Mashing",
    definition_es: "El proceso de mezclar agua caliente con granos molidos para activar las enzimas de la malta, las cuales convierten los almidones complejos del grano en azúcares fermentables simples (principalmente maltosa) y no fermentables (dextrinas).",
    definition_en: "The process of mixing hot water with milled grains to activate malt enzymes, which convert complex grain starches into simple fermentable sugars (mainly maltose) and non-fermentable sugars (dextrins).",
    patterns_es: ["maceraci[oó]n", "maceraciones"],
    patterns_en: ["mashing", "mash", "mashed"]
  },
  {
    id: "flocculation",
    name_es: "Floculación",
    name_en: "Flocculation",
    definition_es: "La capacidad de las células de levadura para agruparse en racimos al final de la fermentación y sedimentarse en el fondo del fermentador, dejando la cerveza más brillante y clarificada. Varía según la cepa de levadura.",
    definition_en: "The ability of yeast cells to clump together into clusters at the end of fermentation and settle to the bottom of the fermenter, leaving the beer brighter and clarified. It varies by yeast strain.",
    patterns_es: ["floculaci[oó]n", "floculaciones"],
    patterns_en: ["flocculation", "flocculate"]
  },
  {
    id: "gravity_og",
    name_es: "Gravedad Original (OG)",
    name_en: "Original Gravity (OG)",
    definition_es: "La medida de la densidad del mosto antes de comenzar la fermentación en relación con la del agua pura. Indica la cantidad de azúcares solubles disueltos en el líquido y determina el potencial alcohólico total de la cerveza.",
    definition_en: "The measure of the wort's density before fermentation starts, relative to pure water. It indicates the amount of dissolved soluble sugars in the liquid and determines the total alcohol potential of the beer.",
    patterns_es: ["gravedad original", "\\bog\\b"],
    patterns_en: ["original gravity", "\\bog\\b"]
  },
  {
    id: "gravity_fg",
    name_es: "Gravedad Final (FG)",
    name_en: "Final Gravity (FG)",
    definition_es: "La medida de la densidad de la cerveza una vez completada por completo la fermentación. Representa la porción de azúcares no fermentables, dextrinas y proteínas residuales que le dan cuerpo y dulzor final a la cerveza.",
    definition_en: "The measure of the beer's density once fermentation is completely finished. It represents the portion of non-fermentable sugars, dextrins, and residual proteins that lend body and final sweetness to the beer.",
    patterns_es: ["gravedad final", "\\bfg\\b"],
    patterns_en: ["final gravity", "\\bfg\\b"]
  },
  {
    id: "ibu",
    name_es: "IBU (Unidades Internacionales de Amargor)",
    name_en: "IBU (International Bitterness Units)",
    definition_es: "Una escala química cuantitativa estándar para medir la concentración de iso-alfa-ácidos solubles provenientes de los lúpulos que aportan amargor a la cerveza. 1 IBU equivale a 1 miligramo de iso-alfa-ácido por litro de cerveza.",
    definition_en: "A standard quantitative chemical scale to measure the concentration of soluble iso-alpha-acids from hops that contribute bitterness to the beer. 1 IBU equals 1 milligram of iso-alpha-acid per liter of beer.",
    patterns_es: ["\\bibus\\b", "\\bibu\\b"],
    patterns_en: ["\\bibus\\b", "\\bibu\\b"]
  },
  {
    id: "srm",
    name_es: "SRM (Método de Referencia Estándar)",
    name_en: "SRM (Standard Reference Method)",
    definition_es: "El sistema espectrofotométrico estándar utilizado por los cerveceros para medir cuantitativamente el color de una cerveza. Varía desde valores muy bajos como 2 (paja pálido) hasta más de 40 (negro opaco e impenetrable).",
    definition_en: "The standard spectrophotometric system used by brewers to quantitatively measure the color of a beer. It ranges from very low values like 2 (pale straw) to over 40 (opaque, impenetrable black).",
    patterns_es: ["\\bsrm\\b"],
    patterns_en: ["\\bsrm\\b"]
  },
  {
    id: "chill_haze",
    name_es: "Turbidez en Frío",
    name_en: "Chill Haze",
    definition_es: "Una turbidez reversible que aparece cuando la cerveza se enfría a temperaturas muy bajas, causada por la precipitación y unión de complejos de proteínas y taninos. Desaparece por completo a medida que la cerveza vuelve a entibiarse.",
    definition_en: "A reversible haziness that appears when beer is chilled to very low temperatures, caused by the precipitation and binding of protein-tannin complexes. It completely disappears as the beer warms back up.",
    patterns_es: ["turbidez en fr[ií]o"],
    patterns_en: ["chill haze"]
  },
  {
    id: "carbonation",
    name_es: "Carbonatación",
    name_en: "Carbonation",
    definition_es: "La cantidad de dióxido de carbono (CO2) gaseoso disuelto en la cerveza. Aporta efervescencia, picor táctil en boca, ayuda a liberar los compuestos aromáticos volátiles hacia la nariz y promueve la retención de la corona de espuma.",
    definition_en: "The amount of carbon dioxide (CO2) gas dissolved in the beer. It contributes effervescence, tactile carbonic bite in the mouth, helps release volatile aromatic compounds to the nose, and promotes head foam retention.",
    patterns_es: ["carbonataci[oó]n", "carbonatada"],
    patterns_en: ["carbonation", "carbonated"]
  },
  {
    id: "conditioning",
    name_es: "Acondicionamiento / Maduración",
    name_en: "Conditioning / Maturation",
    definition_es: "El período de reposo posterior a la fermentación principal donde la cerveza madura. La levadura restante limpia compuestos indeseables, los sabores se asientan, se absorbe el diacetilo y las partículas en suspensión decantan.",
    definition_en: "The rest period following primary fermentation where the beer matures. The remaining yeast cleans up undesirable compounds, flavors settle, diacetyl is absorbed, and suspended particles decant.",
    patterns_es: ["acondicionamiento", "maduraci[oó]n"],
    patterns_en: ["conditioning", "maturation"]
  },
  {
    id: "hops",
    name_es: "Lúpulo",
    name_en: "Hops",
    definition_es: "Las flores cónicas de la planta trepadora Humulus lupulus. Sus glándulas de lupulina contienen resinas que aportan amargor y aceites esenciales que confieren una inmensa gama de aromas y sabores florales, herbales, cítricos o resinosos.",
    definition_en: "The cone-like flowers of the climbing vine Humulus lupulus. Their lupulin glands contain resins that contribute bitterness and essential oils that impart an immense range of floral, herbal, citrus, or resinous aromas and flavors.",
    patterns_es: ["l[uú]pulos", "l[uú]pulo"],
    patterns_en: ["hops", "hop", "hopped", "hoppy"]
  },
  {
    id: "mouthfeel",
    name_es: "Sensación en Boca",
    name_en: "Mouthfeel",
    definition_es: "La gama completa de sensaciones táctiles y no gustativas percibidas en la boca al degustar una cerveza. Incluye el cuerpo, la carbonatación, la calidez del alcohol, la astringencia, el picor carbónico y la cremosidad física.",
    definition_en: "The full range of tactile, non-taste sensations perceived in the mouth when tasting a beer. It includes body, carbonation, alcohol warmth, astringency, carbonic bite, and physical creaminess.",
    patterns_es: ["sensaci[oó]n en boca"],
    patterns_en: ["mouthfeel"]
  },
  {
    id: "lagering",
    name_es: "Lagering / Maduración en Frío",
    name_en: "Lagering / Cold Conditioning",
    definition_es: "El largo período de almacenamiento en frío (cercano a 0°C) de cervezas de baja fermentación (lagers). Favorece la clarificación natural extrema, la precipitación de turbidez y suaviza notablemente el carácter aromático.",
    definition_en: "The long period of cold storage (near 0°C/32°F) of bottom-fermented beers (lagers). It promotes extreme natural clarification, turbidity precipitation, and notably rounds out and smoothens the aromatic character.",
    patterns_es: ["lagering", "maduraci[oó]n en fr[ií]o"],
    patterns_en: ["lagering", "cold conditioning"]
  },
  {
    id: "esters_banana",
    name_es: "Acetato de Isoamilo",
    name_en: "Isoamyl Acetate",
    definition_es: "El éster frutal dominante producido típicamente por levaduras de trigo alemanas (Hefeweizen), el cual imparte el característico olor a plátano maduro o banana. Es un descriptor clave de estilo de esta categoría.",
    definition_en: "The dominant fruity ester typically produced by German wheat yeasts (Hefeweizen), which imparts the characteristic ripe banana aroma. It is a key style descriptor for this category.",
    patterns_es: ["acetato de isoamilo"],
    patterns_en: ["isoamyl acetate"]
  },
  {
    id: "dry_hopping",
    name_es: "Dry Hopping (Lupulado en Seco)",
    name_en: "Dry Hopping",
    definition_es: "La técnica de adición de lúpulos secos directamente a la cerveza fría durante el proceso de maduración o al final de la fermentación activa. Aporta una inmensa intensidad aromática fresca (floral, herbal, cítrica o resinosa) sin añadir amargor perceptible a la cerveza.",
    definition_en: "The technique of adding dry hops directly to cold beer during the maturation process or at the tail end of active fermentation. It contributes an immense, fresh aromatic intensity (floral, herbal, citrusy, or resinous) without adding perceptible bitterness to the beer.",
    patterns_es: ["dry hopping", "lupulado en seco", "dry-hopping"],
    patterns_en: ["dry hopping", "dry-hopping"]
  }
];

export interface TagDefinition {
  tag: string;
  name_es: string;
  name_en: string;
  description_es: string;
  description_en: string;
}

export const TAG_DEFINITIONS_DATA: TagDefinition[] = [
  {
    tag: "hop-forward",
    name_es: "Lúpulo Dominante (Hop-forward)",
    name_en: "Hop-forward",
    description_es: "Estilos donde el lúpulo es el protagonista absoluto en aroma, sabor y amargor. Los ejemplos típicos son las IPAs y las Pale Ales.",
    description_en: "Styles where hops are the main protagonist in aroma, flavor, and bitterness. Typical examples are IPAs and Pale Ales."
  },
  {
    tag: "malty",
    name_es: "Malteado Dominante (Malty)",
    name_en: "Malty",
    description_es: "Estilos donde predominan los sabores dulces y complejos de las maltas (pan, caramelo, toffee, nuez, chocolate, torrefacto). El lúpulo juega un rol secundario de soporte.",
    description_en: "Styles dominated by the sweet and complex flavors of malts (bread, caramel, toffee, nut, chocolate, roast). Hops play a secondary supporting role."
  },
  {
    tag: "balanced",
    name_es: "Balanceado (Balanced)",
    name_en: "Balanced",
    description_es: "Estilos donde la dulzura de la malta y el amargor del lúpulo se encuentran en perfecta armonía y equilibrio, sin que ninguno eclipse al otro de forma dominante.",
    description_en: "Styles where malt sweetness and hop bitterness are in perfect harmony and equilibrium, with neither dominantly eclipsing the other."
  },
  {
    tag: "sour",
    name_es: "Agrio / Ácido (Sour)",
    name_en: "Sour",
    description_es: "Cervezas caracterizadas por una acidez intencional y refrescante generada por bacterias productoras de ácido láctico o acético (como Lactobacillus, Pediococcus).",
    description_en: "Beers characterized by an intentional and refreshing acidity generated by lactic or acetic acid-producing bacteria (like Lactobacillus, Pediococcus)."
  },
  {
    tag: "wild",
    name_es: "Fermentación Salvaje (Wild)",
    name_en: "Wild / Wild-fermented",
    description_es: "Cervezas fermentadas con microflora no convencional o salvaje (como levaduras Brettanomyces o cultivos mixtos), aportando perfiles rústicos, animales (funk) o de cuero.",
    description_en: "Beers fermented with unconventional or wild microflora (such as Brettanomyces yeasts or mixed cultures), contributing rustic, funky, or leathery profiles."
  },
  {
    tag: "session-strength",
    name_es: "Fuerza de Sesión (Session)",
    name_en: "Session Strength",
    description_es: "Cervezas de baja graduación alcohólica (generalmente por debajo de 4.0% ABV) diseñadas para ser sumamente bebibles en cantidades moderadas durante una 'sesión' prolongada.",
    description_en: "Low-alcohol beers (generally below 4.0% ABV) designed to be highly drinkable in moderate quantities during an extended 'session'."
  },
  {
    tag: "standard-strength",
    name_es: "Fuerza Estándar (Standard)",
    name_en: "Standard Strength",
    description_es: "El rango de graduación alcohólica más común y convencional para la mayoría de estilos de cerveza comerciales (generalmente entre 4.0% y 6.0% ABV).",
    description_en: "The most common and conventional alcohol content range for most commercial beer styles (generally between 4.0% and 6.0% ABV)."
  },
  {
    tag: "high-strength",
    name_es: "Fuerza Alta (High Strength)",
    name_en: "High Strength",
    description_es: "Cervezas con un contenido de alcohol más elevado de lo normal (generalmente entre 6.0% y 9.0% ABV), aportando mayor cuerpo, calidez alcohólica y complejidad.",
    description_en: "Beers with a higher than normal alcohol content (generally between 6.0% and 9.0% ABV), contributing greater body, alcohol warmth, and complexity."
  },
  {
    tag: "very-high-strength",
    name_es: "Fuerza Muy Alta (Very High Strength)",
    name_en: "Very High Strength",
    description_es: "Cervezas extremadamente fuertes y corpulentas con graduaciones superiores al 9.0% ABV (ej: Imperial Stouts, Barleywines). Tienen un carácter alcohólico cálido y complejo.",
    description_en: "Extremely strong, full-bodied beers with alcohol content exceeding 9.0% ABV (e.g. Imperial Stouts, Barleywines). They have a warm and complex alcohol character."
  },
  {
    tag: "historical",
    name_es: "Estilo Histórico (Historical)",
    name_en: "Historical Style",
    description_es: "Estilos de cerveza tradicionales del pasado que habían declinado en popularidad o desaparecido, pero que han sido recreados por cerveceros modernos siguiendo recetas históricas.",
    description_en: "Traditional beer styles from the past that had declined in popularity or disappeared, but have been recreated by modern brewers following historical recipes."
  },
  {
    tag: "craft-style",
    name_es: "Estilo Artesanal (Craft)",
    name_en: "Craft Style",
    description_es: "Estilos modernos desarrollados o revitalizados principalmente por el movimiento mundial de cervecerías artesanales e independientes en las últimas décadas.",
    description_en: "Modern styles developed or revitalized primarily by the global craft and independent brewing movement in recent decades."
  },
  {
    tag: "top-fermented",
    name_es: "Fermentación Alta / Ale (Top-fermented)",
    name_en: "Top-fermented (Ale)",
    description_es: "Cervezas elaboradas con levaduras Saccharomyces cerevisiae que fermentan a temperaturas más cálidas (15-22°C) y tienden a flotar en la superficie, produciendo ésteres frutales.",
    description_en: "Beers brewed with Saccharomyces cerevisiae yeast that ferments at warmer temperatures (15-22°C/59-72°F) and tends to rise to the surface, producing fruity esters."
  },
  {
    tag: "bottom-fermented",
    name_es: "Fermentación Baja / Lager (Bottom-fermented)",
    name_en: "Bottom-fermented (Lager)",
    description_es: "Cervezas elaboradas con levaduras Saccharomyces pastorianus que fermentan a temperaturas frías (7-13°C) en el fondo del tanque, logrando perfiles limpios y sin ésteres.",
    description_en: "Beers brewed with Saccharomyces pastorianus yeast that ferments at cold temperatures (7-13°C/45-55°F) at the bottom of the tank, yielding clean profiles free of esters."
  }
];
